---
# tasks file for newrole
    - include_tasks: tasks/common.yml
    - include_tasks: tasks/apache.yml
    - include_tasks: tasks/php.yml
    - include_tasks: tasks/mysql.yml
    - include_tasks: tasks/composer.yml
    - include_tasks: tasks/drush.yml
    - include_tasks: tasks/drupal.yml

